//---------------------------------------------------------------------------

#ifndef satisH
#define satisH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <DBGrids.hpp>
#include <ExtCtrls.hpp>
#include <Grids.hpp>
#include <ToolWin.hpp>
#include <ImgList.hpp>
#include <DBCtrls.hpp>
#include <Menus.hpp>
#include <Db.hpp>
#include <DBTables.hpp>
#include <Mask.hpp>
#include <Buttons.hpp>
//---------------------------------------------------------------------------
class TfrmSatisFisi : public TForm
{
__published:	// IDE-managed Components
    TImageList *ImageList1;
    TTable *tblSTOKSATIS;
    TDataSource *dsrcSTOKSATIS;
    TDataSource *dsrcSATICI;
    TQuery *querySATICI;
    TAutoIncField *tblSTOKSATISOTOMATIK_SAYI;
    TBooleanField *tblSTOKSATISHAREKET_TURU;
    TDateField *tblSTOKSATISTARIH;
    TStringField *tblSTOKSATISMUSTERI_NO;
    TStringField *tblSTOKSATISMUSTERI_ADI;
    TStringField *tblSTOKSATISKAYIT_NO;
    TStringField *tblSTOKSATISSATICI;
    TCurrencyField *tblSTOKSATISBIRIM_FIYATI;
    TFloatField *tblSTOKSATISMAL_ADEDI;
    TDateField *tblSTOKSATISILK_TAKSIT_TARIHI;
    TCurrencyField *tblSTOKSATISMAL_BEDELI;
    TCurrencyField *tblSTOKSATISPESINAT;
    TFloatField *tblSTOKSATISTAKSIT_SAYISI;
    TCurrencyField *tblSTOKSATISTAKSIT_TUTARI;
    TCurrencyField *tblSTOKSATISKALAN_BORC;
    TMemoField *tblSTOKSATISACIKLAMA;
    TStringField *tblSTOKSATISURUN_NO;
    TStringField *tblSTOKSATISURUN_ADI;
    TDataSource *dsrcMUSTERI;
    TTable *tblMUSTERI;
    TStringField *tblMUSTERIM_NO;
    TStringField *tblMUSTERIM_ADI;
    TStringField *tblMUSTERIM_SOYADI;
    TStringField *tblMUSTERIM_CADDE;
    TStringField *tblMUSTERIM_SOKAK;
    TStringField *tblMUSTERIM_KAPINO;
    TStringField *tblMUSTERIM_BOLGE;
    TStringField *tblMUSTERIM_MAHALLE;
    TStringField *tblMUSTERIM_EVTEL;
    TStringField *tblMUSTERIM_CEPTEL;
    TStringField *tblMUSTERIM_ISTEL1;
    TStringField *tblMUSTERIM_ISTEL2;
    TStringField *tblMUSTERIK_ADI;
    TStringField *tblMUSTERIK_SOYADI;
    TStringField *tblMUSTERIK_CADDE;
    TStringField *tblMUSTERIK_SOKAK;
    TStringField *tblMUSTERIK_KAPINO;
    TStringField *tblMUSTERIK_BOLGE;
    TStringField *tblMUSTERIK_MAHALLE;
    TStringField *tblMUSTERIK_EVTEL;
    TStringField *tblMUSTERIK_CEPTEL;
    TStringField *tblMUSTERIK_ISTEL1;
    TStringField *tblMUSTERIK_ISTEL2;
    TStringField *tblMUSTERIDURUM;
    TMemoField *tblMUSTERIKARALISTE_ACIKLAMASI;
    TStringField *tblMUSTERIKARA_LISTE;
    TCurrencyField *tblMUSTERIAYLIK_TAKSIT;
    TCurrencyField *tblMUSTERIMAL_BEDELI;
    TCurrencyField *tblMUSTERIODENEN_TUTAR;
    TCurrencyField *tblMUSTERIKALAN_BORC;
    TDateField *tblMUSTERISON_TAKSIT_TARIHI;
    TStringField *tblSTOKSATISMUSTERI_SOYADI;
    TDataSource *dsrcTAKSIT;
    TTable *tblTAKSIT;
    TQuery *queryTAKSITLISTE;
    TDataSource *dsrcTAKSITLISTE;
    TDateField *tblTAKSITVADE_TARIHI;
    TCurrencyField *tblTAKSITTAKSIT_TUTARI;
    TDateField *tblTAKSITODEME_TARIHI;
    TCurrencyField *tblTAKSITODEME_TUTARI;
    TCurrencyField *tblTAKSITKALAN_BAKIYE;
    TFloatField *tblTAKSITODEME_FISI;
    TStringField *tblTAKSITMUSTERI_KODU;
    TGroupBox *GroupBox1;
    TPageControl *PageControl2;
    TTabSheet *TabSheet3;
    TGroupBox *GroupBox5;
    TLabel *Label18;
    TLabel *Label20;
    TLabel *Label21;
    TLabel *Label22;
    TLabel *Label11;
    TLabel *Label12;
    TLabel *Label13;
    TLabel *Label14;
    TLabel *Label15;
    TLabel *Label23;
    TSpeedButton *SpeedButton1;
    TDBEdit *TOPMALBED_Edit;
    TDBEdit *PESINAT_Edit;
    TDBEdit *TAKSITSAY_Edit;
    TDBEdit *TAKSITTUT_Edit;
    TDBEdit *TOPLAMBORC_Edit;
    TDBEdit *URUNKODU_Edit;
    TDBEdit *URUNADI_Edit;
    TDBEdit *BIRIMFIYATI_Edit;
    TDBEdit *MALADETI_Edit;
    TDBEdit *ILKTAKSITTARIHI_Edit;
    TTabSheet *TabSheet4;
    TDBGrid *DBGrid2;
    TTabSheet *TabSheet1;
    TDBMemo *ACIKLAMA_Memo;
    TGroupBox *GroupBox2;
    TLabel *Label1;
    TLabel *Label3;
    TLabel *Label4;
    TLabel *Label5;
    TLabel *Label2;
    TLabel *Label6;
    TLabel *Label7;
    TLabel *Label8;
    TLabel *Label9;
    TLabel *Label10;
    TSpeedButton *SpeedButton2;
    TDBEdit *MNO_Edit;
    TDBEdit *MADI_Edit;
    TDBEdit *MSOYADI_Edit;
    TDBEdit *MBOLGE_Edit;
    TDBEdit *MCADDE_Edit;
    TDBEdit *MSOKAK_Edit;
    TDBEdit *MKAPINO_Edit;
    TDBEdit *M_EVTEL_Edit;
    TDBEdit *MCEPTEL_Edit;
    TDBEdit *MMAHALLE_Edit;
    TGroupBox *GroupBox4;
    TLabel *Label16;
    TLabel *Label17;
    TLabel *Label19;
    TDBEdit *KAYITNO_Edit;
    TDBEdit *TARIH_Edit;
    TDBLookupComboBox *SATICI_Combo;
    TToolBar *ToolBar1;
    TToolButton *tbtnYENI;
    TToolButton *tbtnKAYDET;
    TToolButton *tbtnSIL;
    TToolButton *ToolButton6;
    TToolButton *tbtnAC;
    TToolButton *ToolButton7;
    TToolButton *tbtnYAZDIR;
    TCheckBox *KUTU_Check;
    TDataSource *dsrcKONTROL;
    TQuery *queryKONTROL;
    TStringField *tblTAKSITAY_YIL;
    TQuery *queryODEME;
    TIntegerField *queryODEMEOTOMATIK_SAYI;
    TStringField *queryODEMEMNO;
    TStringField *queryODEMESATICI;
    TMemoField *queryODEMEACIKLAMA;
    TDateField *queryODEMEODEME_TARIHI;
    TCurrencyField *queryODEMEODEME_TUTARI;
    TCurrencyField *queryODEMEBAKIYE;
    TStringField *queryODEMEMADI;
    TStringField *queryODEMEMSOYADI;
    TBooleanField *queryODEMEONAY;
    TQuery *queryTAKSITSIL;
    TAutoIncField *tblTAKSITOTOMATIK_SAYI;
    TIntegerField *tblTAKSITSATIS_FISI;
    TQuery *queryTAKSITDUZEN;
    TIntegerField *queryTAKSITDUZENOTOMATIK_SAYI;
    TDateField *queryTAKSITDUZENVADE_TARIHI;
    TCurrencyField *queryTAKSITDUZENTAKSIT_TUTARI;
    TDateField *queryTAKSITDUZENODEME_TARIHI;
    TCurrencyField *queryTAKSITDUZENODEME_TUTARI;
    TCurrencyField *queryTAKSITDUZENKALAN_BAKIYE;
    TFloatField *queryTAKSITDUZENODEME_FISI;
    TIntegerField *queryTAKSITDUZENSATIS_FISI;
    TStringField *queryTAKSITDUZENMUSTERI_KODU;
    TStringField *queryTAKSITDUZENAY_YIL;
    TTable *tblTAKSITDEGIS;
    TAutoIncField *tblTAKSITDEGISOTOMATIK_SAYI;
    TDateField *tblTAKSITDEGISVADE_TARIHI;
    TCurrencyField *tblTAKSITDEGISTAKSIT_TUTARI;
    TDateField *tblTAKSITDEGISODEME_TARIHI;
    TCurrencyField *tblTAKSITDEGISODEME_TUTARI;
    TCurrencyField *tblTAKSITDEGISKALAN_BAKIYE;
    TFloatField *tblTAKSITDEGISODEME_FISI;
    TStringField *tblTAKSITDEGISMUSTERI_KODU;
    TStringField *tblTAKSITDEGISAY_YIL;
    TIntegerField *tblTAKSITDEGISSATIS_FISI;
    TQuery *queryTAKSITHAR;
    TIntegerField *queryTAKSITHAROTOMATIK_SAYI;
    TDateField *queryTAKSITHARVADE_TARIHI;
    TCurrencyField *queryTAKSITHARTAKSIT_TUTARI;
    TDateField *queryTAKSITHARODEME_TARIHI;
    TCurrencyField *queryTAKSITHARODEME_TUTARI;
    TCurrencyField *queryTAKSITHARKALAN_BAKIYE;
    TFloatField *queryTAKSITHARODEME_FISI;
    TStringField *queryTAKSITHARMUSTERI_KODU;
    TStringField *queryTAKSITHARAY_YIL;
    TIntegerField *queryTAKSITHARSATIS_FISI;
    TQuery *querySATIS;
    TIntegerField *querySATISOTOMATIK_SAYI;
    TBooleanField *querySATISHAREKET_TURU;
    TDateField *querySATISTARIH;
    TStringField *querySATISMUSTERI_NO;
    TStringField *querySATISMUSTERI_ADI;
    TStringField *querySATISMUSTERI_SOYADI;
    TStringField *querySATISKAYIT_NO;
    TStringField *querySATISSATICI;
    TCurrencyField *querySATISBIRIM_FIYATI;
    TFloatField *querySATISMAL_ADEDI;
    TDateField *querySATISILK_TAKSIT_TARIHI;
    TCurrencyField *querySATISMAL_BEDELI;
    TCurrencyField *querySATISPESINAT;
    TFloatField *querySATISTAKSIT_SAYISI;
    TCurrencyField *querySATISTAKSIT_TUTARI;
    TCurrencyField *querySATISKALAN_BORC;
    TMemoField *querySATISACIKLAMA;
    TStringField *querySATISURUN_NO;
    TStringField *querySATISURUN_ADI;
    TQuery *queryODEMESIL;
    TQuery *queryODEMEFISI;
    TIntegerField *queryODEMEFISIOTOMATIK_SAYI;
    TStringField *queryODEMEFISIMNO;
    TStringField *queryODEMEFISISATICI;
    TMemoField *queryODEMEFISIACIKLAMA;
    TDateField *queryODEMEFISIODEME_TARIHI;
    TCurrencyField *queryODEMEFISIODEME_TUTARI;
    TCurrencyField *queryODEMEFISIBAKIYE;
    TStringField *queryODEMEFISIMADI;
    TStringField *queryODEMEFISIMSOYADI;
    TBooleanField *queryODEMEFISIONAY;
    TQuery *queryTUTAR;
    TQuery *queryTAKSIT;
    TCurrencyField *queryTAKSITODEME_TUTARI;
    TCurrencyField *queryTAKSITKALAN_BAKIYE;
    TCurrencyField *queryTAKSITTAKSIT_TUTARI;
    TStringField *tblTAKSITTAKSIT_TURU;
    TIntegerField *queryTAKSITSILOTOMATIK_SAYI;
    TDateField *queryTAKSITSILVADE_TARIHI;
    TCurrencyField *queryTAKSITSILTAKSIT_TUTARI;
    TDateField *queryTAKSITSILODEME_TARIHI;
    TCurrencyField *queryTAKSITSILODEME_TUTARI;
    TCurrencyField *queryTAKSITSILKALAN_BAKIYE;
    TFloatField *queryTAKSITSILODEME_FISI;
    TIntegerField *queryTAKSITSILSATIS_FISI;
    TStringField *queryTAKSITSILMUSTERI_KODU;
    TStringField *queryTAKSITSILAY_YIL;
    TStringField *queryTAKSITSILTAKSIT_TURU;
    TStringField *queryTAKSITDUZENTAKSIT_TURU;
    TStringField *queryTAKSITHARTAKSIT_TURU;
    TQuery *queryDEVIRKONTROL;
    TQuery *queryDEVIRSIL;
    TIntegerField *queryDEVIRKONTROLOTOMATIK_SAYI;
    TDateField *queryDEVIRKONTROLVADE_TARIHI;
    TCurrencyField *queryDEVIRKONTROLTAKSIT_TUTARI;
    TDateField *queryDEVIRKONTROLODEME_TARIHI;
    TCurrencyField *queryDEVIRKONTROLODEME_TUTARI;
    TCurrencyField *queryDEVIRKONTROLKALAN_BAKIYE;
    TFloatField *queryDEVIRKONTROLODEME_FISI;
    TIntegerField *queryDEVIRKONTROLSATIS_FISI;
    TStringField *queryDEVIRKONTROLMUSTERI_KODU;
    TStringField *queryDEVIRKONTROLAY_YIL;
    TStringField *queryDEVIRKONTROLTAKSIT_TURU;
    TQuery *querySATISNOTAKSIT;
    TIntegerField *queryDEVIRSILOTOMATIK_SAYI;
    TDateField *queryDEVIRSILVADE_TARIHI;
    TCurrencyField *queryDEVIRSILTAKSIT_TUTARI;
    TDateField *queryDEVIRSILODEME_TARIHI;
    TCurrencyField *queryDEVIRSILODEME_TUTARI;
    TCurrencyField *queryDEVIRSILKALAN_BAKIYE;
    TFloatField *queryDEVIRSILODEME_FISI;
    TIntegerField *queryDEVIRSILSATIS_FISI;
    TStringField *queryDEVIRSILMUSTERI_KODU;
    TStringField *queryDEVIRSILAY_YIL;
    TStringField *queryDEVIRSILTAKSIT_TURU;
    TIntegerField *querySATISNOTAKSITOTOMATIK_SAYI;
    TDateField *querySATISNOTAKSITVADE_TARIHI;
    TCurrencyField *querySATISNOTAKSITTAKSIT_TUTARI;
    TDateField *querySATISNOTAKSITODEME_TARIHI;
    TCurrencyField *querySATISNOTAKSITODEME_TUTARI;
    TCurrencyField *querySATISNOTAKSITKALAN_BAKIYE;
    TFloatField *querySATISNOTAKSITODEME_FISI;
    TIntegerField *querySATISNOTAKSITSATIS_FISI;
    TStringField *querySATISNOTAKSITMUSTERI_KODU;
    TStringField *querySATISNOTAKSITAY_YIL;
    TStringField *querySATISNOTAKSITTAKSIT_TURU;
    TIntegerField *queryODEMEFISITAKSIT_NO;
    void __fastcall tbtnYENIClick(TObject *Sender);
    TDateTime __fastcall TarihiBul(TDateTime Tarih, int TaksitSayisi);
    void __fastcall TARIH_EditChange(TObject *Sender);
    void __fastcall SATICI_ComboClick(TObject *Sender);
    void __fastcall MNO_EditChange(TObject *Sender);
    void __fastcall URUNKODU_EditChange(TObject *Sender);
    void __fastcall BIRIMFIYATI_EditChange(TObject *Sender);
    TDateTime __fastcall TarihiDegistir(TDateTime IlkTarih, TDateTime TaksitTarihi);
    void __fastcall TaksitOlustur(void);
    void __fastcall KayitKontrol(void);
    bool __fastcall SatisFisiSayisi(void);
    void __fastcall MALADETI_EditChange(TObject *Sender);
    void __fastcall TaksitSifirla(TDateTime Tarih);
    void __fastcall ILKTAKSITTARIHI_EditChange(TObject *Sender);
    void __fastcall TOPMALBED_EditChange(TObject *Sender);
    void __fastcall PESINAT_EditChange(TObject *Sender);
    void __fastcall TAKSITSAY_EditChange(TObject *Sender);
    void __fastcall TAKSITTUT_EditChange(TObject *Sender);
    void __fastcall TOPLAMBORC_EditChange(TObject *Sender);
    void __fastcall TaksitBakiyeBul(TDateTime Tarih);
    bool __fastcall OdemeBakiyeBul(TDateTime Tarih);
    void __fastcall ACIKLAMA_MemoChange(TObject *Sender);
    void __fastcall TARIH_EditKeyPress(TObject *Sender, char &Key);
    void __fastcall SATICI_ComboKeyPress(TObject *Sender, char &Key);
    void __fastcall BIRIMFIYATI_EditKeyPress(TObject *Sender, char &Key);
    void __fastcall MALADETI_EditKeyPress(TObject *Sender, char &Key);
    void __fastcall ILKTAKSITTARIHI_EditKeyPress(TObject *Sender,
          char &Key);
    void __fastcall PESINAT_EditKeyPress(TObject *Sender, char &Key);
    void __fastcall TAKSITSAY_EditKeyPress(TObject *Sender, char &Key);
    void __fastcall SpeedButton2Click(TObject *Sender);
    void __fastcall SpeedButton1Click(TObject *Sender);
    void __fastcall Kilit(void);
    void __fastcall Anahtar(void);
    void __fastcall TaksitDuzenle(TDateTime Tarih);
    void __fastcall KaydiKapa(void);
    void __fastcall Hesapla(void);
    void __fastcall tbtnKAYDETClick(TObject *Sender);
    void __fastcall tbtnACClick(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall FormShow(TObject *Sender);
    void __fastcall tbtnSILClick(TObject *Sender);
    void __fastcall tbtnYAZDIRClick(TObject *Sender);
private:	// User declarations
public:		// User declarations
    __fastcall TfrmSatisFisi(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TfrmSatisFisi *frmSatisFisi;
//---------------------------------------------------------------------------
#endif
